# Dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, rating, timestamp, history]
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50

# Model config
model: SASRec
embedding_size: 768  # Change this to match BLAIR embedding size
hidden_size: 768     # Ensure this matches the embedding size
num_layers: 1
dropout_prob: 0.3

# Training config
train_config:
    epochs: 500
    train_batch_size: 512

# Evaluation config
eval_config:
    eval_batch_size: 512
    eval_args:
        group_by: user
        order: TO
        split: {'LS': 'valid_and_test'}
        mode: full
    metrics: [Recall, NDCG]
    topk: [10, 50]
    valid_metric: NDCG@10
    metric_decimal_place: 4

# Logging config
logging_config:
    version: 1
    formatters:
        simple:
            format: '%(asctime)s - %(levellevelame)s - %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: INFO
            formatter: simple
            stream: ext://sys.stdout
    root:
        level: INFO
        handlers: [console]

# Domain config
domains: [All_Beauty, Video_Games, Baby_Products]
